name: Deploy Docker Image to AWS ECR and EC2 with Debugging

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  deploy-to-ec2:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the Code
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    # Step 2: Configure AWS CLI
    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    # Step 3: Log in to Amazon ECR
    - name: Log in to Amazon ECR
      run: |
        echo "Authenticating with AWS ECR..."
        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 476424248806.dkr.ecr.ap-south-1.amazonaws.com

    # Step 4: Build and Push Docker Image to ECR
    - name: Build and Push Docker Image
      run: |
        echo "Building Docker Image..."
        ECR_URI=476424248806.dkr.ecr.ap-south-1.amazonaws.com/sumit-ecr
        docker build -t $ECR_URI:latest .
        echo "Pushing Docker Image to ECR..."
        docker push $ECR_URI:latest

    # Step 5: SSH into EC2 and Deploy Docker Container
    - name: Deploy Docker Container on EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}
        username: ubuntu  # Use `ec2-user` for Amazon Linux
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          set -e  # Stop the script on the first error

          echo "Updating EC2 instance..."
          sudo apt update -y || sudo yum update -y

          echo "Installing Docker (if not installed)..."
          if ! [ -x "$(command -v docker)" ]; then
            sudo apt install -y docker.io || sudo yum install -y docker
            sudo systemctl start docker
            sudo systemctl enable docker
            echo "Docker installed successfully!"
          else
            echo "Docker is already installed."
          fi

          echo "Checking Docker status..."
          sudo systemctl status docker || true

          echo "Authenticating EC2 instance with ECR..."
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 476424248806.dkr.ecr.ap-south-1.amazonaws.com

          echo "Pulling the Docker image from ECR..."
          docker pull 476424248806.dkr.ecr.ap-south-1.amazonaws.com/sumit-ecr:latest

          echo "Checking if a container is already running..."
          docker ps -a || true

          echo "Stopping any existing container..."
          docker stop sumit-ecr-container || true
          docker rm sumit-ecr-container || true

          echo "Starting the Docker container..."
          docker run -d --name sumit-ecr-container -p 80:80 476424248806.dkr.ecr.ap-south-1.amazonaws.com/sumit-ecr:latest

          echo "Deployment Complete!"
          echo "Listing running containers..."
          docker ps

          echo "Checking container logs..."
          docker logs sumit-ecr-container || true
        debug: true

    # Step 6: Verify Application Health
    - name: Health Check
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "Performing health check..."
          curl -f http://localhost:80 || echo "Application is not responding."
        debug: true
