name: Deploy Docker Image to AWS ECR

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  deploy-to-ecr:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Configure AWS CLI
    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Step 3: Log in to AWS ECR
    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 123456789012.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

    # Step 4: Build and Push Docker Image to ECR
    - name: Build and Push Docker Image
      run: |
        ECR_URI=123456789012.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/node-kubernative
        docker build -t $ECR_URI:latest .
        docker push $ECR_URI:latest
