name: Deploy Docker Image to AWS ECR and Kubernetes

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  deploy-to-ecr:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Configure AWS CLI
    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    # Step 3: Log in to AWS ECR
    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 476424248806.dkr.ecr.ap-south-1.amazonaws.com

    # Step 4: Build and Push Docker Image to ECR
    - name: Build and Push Docker Image
      run: |
        ECR_URI=476424248806.dkr.ecr.ap-south-1.amazonaws.com/sumit-ecr
        docker build -t $ECR_URI:latest .
        docker push $ECR_URI:latest

    # Step 5: SSH into EC2 and Deploy to Kubernetes
    - name: Deploy to Kubernetes on EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "Authenticating with AWS ECR"
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 476424248806.dkr.ecr.ap-south-1.amazonaws.com
          echo "Creating Kubernetes ImagePullSecrets"
          kubectl create secret docker-registry ecr-registry-secret \
            --docker-server=476424248806.dkr.ecr.ap-south-1.amazonaws.com \
            --docker-username=AWS \
            --docker-password=$(aws ecr get-login-password --region ap-south-1) \
            --namespace default --dry-run=client -o yaml | kubectl apply -f -
          echo "Applying Kubernetes Deployment"
          kubectl apply -f /path/to/deployment.yaml
          echo "Applying Kubernetes Service"
          kubectl apply -f /path/to/service.yaml
