name: Deploy Docker Image to AWS ECR and Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy-to-ecr-and-k8s:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Configure AWS CLI
    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    # Step 3: Log in to AWS ECR
    - name: Log in to Amazon ECR
      run: |
        echo "Authenticating with AWS ECR..."
        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 476424248806.dkr.ecr.ap-south-1.amazonaws.com

    # Step 4: Build and Push Docker Image to ECR
    - name: Build and Push Docker Image
      run: |
        echo "Building Docker Image..."
        ECR_URI=476424248806.dkr.ecr.ap-south-1.amazonaws.com/sumit-ecr
        docker build -t $ECR_URI:latest .
        echo "Pushing Docker Image to ECR..."
        docker push $ECR_URI:latest
