name: Deploy to Kubernetes

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build and Push Docker Image
    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/node-kubernative:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/node-kubernative:latest

    # Step 4: Set up kubectl
    - name: Set up kubectl
      run: |
        mkdir -p ~/.kube  # Create the .kube directory
        echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > ~/.kube/config  # Decode and write kubeconfig
        kubectl cluster-info  # Verify kubectl can connect to the cluster

    # Step 5: Deploy Kubernetes Manifests
    - name: Deploy Kubernetes Manifests
      run: |
        kubectl apply -f k8s-manifests/deployment.yaml
        kubectl apply -f k8s-manifests/service.yaml

    # Step 6: Verify Deployment
    - name: Check Deployment Status
      run: |
        kubectl get pods
        kubectl get services
