name: Deploy ECR Image to EC2

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy-to-ec2:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Configure AWS CLI
    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    # Step 3: Log in to ECR
    - name: Log in to Amazon ECR
      run: |
        echo "Authenticating with AWS ECR..."
        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 476424248806.dkr.ecr.ap-south-1.amazonaws.com

    # Step 4: SSH into EC2 and Deploy the Docker Container
    - name: Deploy Docker Container on EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}
        username: ubuntu  # Update if using Ubuntu or other OS (e.g., ubuntu)
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "Updating EC2 instance..."
          sudo yum update -y || sudo apt update -y

          echo "Installing Docker (if not installed)..."
          if ! [ -x "$(command -v docker)" ]; then
            sudo yum install -y docker || sudo apt install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
          fi

          echo "Authenticating EC2 instance with ECR..."
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 476424248806.dkr.ecr.ap-south-1.amazonaws.com

          echo "Pulling the Docker image from ECR..."
          docker pull 476424248806.dkr.ecr.ap-south-1.amazonaws.com/sumit-ecr:latest

          echo "Running the Docker container..."
          docker stop sumit-ecr-container || true
          docker rm sumit-ecr-container || true
          docker run -d --name sumit-ecr-container -p 80:80 476424248806.dkr.ecr.ap-south-1.amazonaws.com/sumit-ecr:latest

          echo "Deployment Complete!"
